{% set name = "jupyterbook-latex" %}
{% set pip_name = name.replace("-", "_") %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz
  sha256: 2606e27e285d58cf8a5d9fad0b0f79a0180604e15c641a6790a4bd81667f3d63

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sphinx >=3,<4
    - myst-nb
    - pyyaml
    # TODO: should be fixed in jupyter-cache, but....
    - sqlalchemy >=1.3.12,<1.4
    # this is a no-op on 3.9
    - importlib_resources


test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jupyterbook_latex
    - jupyterbook_latex.theme

about:
  home: https://github.com/executablebooks/jupyterbook-latex
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Jupyterbook-latex: Supporting LaTeX infrastructure for Jupyter Book'
  dev_url: https://github.com/executablebooks/jupyterbook-latex

extra:
  recipe-maintainers:
    - AakashGfude
    - conda-forge/jupyter-book
